### ISSUE TITLE
Works first time, but schedules time wrong causing it to be unusable

### ISSUE THREAD

**Issue by adrianwtam** [TerminatorIsGod/CSGORoll-Daily-Rewards-Bot#10]
Your code runs and logs the time, then does the dailies and exits
This causes the time scheduling on task scheduler to be -2 or -3 minutes from the time the dailies are done
Technically the code waits, but in practice it just stops waiting for LV40+ cases

I would just collect the time after the dailies are done and put that into task scheduler

**Comment by TerminatorIsGod** [comment]
It does grab the time after the dailies are done. After it sees there are no more dailies left to claim within the next 5 minutes, it will grab the shortest time left and set that.

Can you explain more what you mean by it stops waiting for the LV40+ cases? What's the time left on the cases? Does it claim them? If it does claim them, how long does it wait after the timer? 

Feel free to include anything else you believe that can be useful.
