### ISSUE TITLE
After finishing a few successful days of claiming, the site starts to not load

### ISSUE THREAD

**Issue by adrianwtam** [TerminatorIsGod/CSGORoll-Daily-Rewards-Bot#11]
![image](https://github.com/TerminatorIsGod/CSGORoll-Daily-Rewards-Bot/assets/65895954/98529f28-3984-497a-8a26-a1a4296addb0)

It gets stuck on this page and you can see the csgoroll loading logo down there
Pretty easy fix. Just reloading the page will work, but it would be great if it's automatically built into the code 👍

**Comment by TerminatorIsGod** [comment]
CSGORoll did an update that has messed stuff up, I need to figure out what they did exactly.

It is supposed to automatically reload the page, ill have to look into this.

**Comment by TerminatorIsGod** [comment]
I have just released a [new version](https://github.com/TerminatorIsGod/CSGORoll-Daily-Rewards-Bot/releases/tag/Release_v1.1.8) that should fix the problem. Let me know if you are still having any issues. If you do run into any issues, if the program is still open, please copy and send me all the text inside the console of the program. _You can do this by left-clicking in the console then do Ctrl + A to select everything, then Ctrl + C to copy._
