### ISSUE TITLE
[Request] Discord Webhook

### ISSUE THREAD

**Issue by notcreeperdude** [TerminatorIsGod/CSGORoll-Daily-Rewards-Bot#15]
Hi, just wondering if it would be possible to add a discord webhook compatibility to put a message in a discord channel when the cases have been opened or even better, with current balance. 
Im running this on my home server under a VM with very low resources given to it so occasionally it crashes and the VM needs a reboot so it would be quite useful if a possibility.
Thanks :)

**Comment by TerminatorIsGod** [comment]
I can definitely implement that as a feature, it should be relatively simple to add. I'll be able to implement it within the next week or two.

**Comment by TerminatorIsGod** [comment]
Added the requested feature in the [latest version](https://github.com/TerminatorIsGod/CSGORoll-Daily-Rewards-Bot/releases/latest). If you have auto update turned on (on by default) it should automatically update to this new version. 

Changelog/how to set up:

> Added support for Discord Webhook messages to send a notification every time it finishes running with the username and balance. To set up webhooks edit 'CSGORollDailyCollector.exe.config', on line 6 set the value to whatever your webhook URL is from discord.
> 
> Example: <add key="discordWebhookURL" `value="https://discord.com/api/webhooks/1307902738264231967/AGMeuh09iANrXOPgL_X-oxnzXAnbQ4iEu32WQaoeIj8j5p70rtgkbVxxYDboM0JyHon8" /> `
