### ISSUE TITLE
Doesn't collect in sleep mode

### ISSUE THREAD

**Issue by evenlk** [TerminatorIsGod/CSGORoll-Daily-Rewards-Bot#3]
It doesn't collect when the computer is in sleep mode. Exe was running before computer went into sleep mode, when the daily reward cases unlocked it didn't open the cases before the computer was in on mode. 

Help appreciated.

**Comment by TerminatorIsGod** [comment]
There was a bug because of the christmas event. It is fixed in the latest release.
