### ISSUE TITLE
Doesn’t always collect all daily cases

### ISSUE THREAD

**Issue by evenlk** [TerminatorIsGod/CSGORoll-Daily-Rewards-Bot#5]
Hi,

So there is an issue where it doesn’t always collect all the cases. There is like a 50/50 chance that it will miss 1-2 cases every day. Random what cases it will miss.

**Comment by TerminatorIsGod** [comment]
Odd, I have had a few people test it with all 11 cases able to open them perfectly fine consistently. How fast is your internet speed and what is your CPU? I am wondering if it's possible that it lags out and is causing the timing to get messed up.

**Comment by evenlk** [comment]
> Odd, I have had a few people test it with all 11 cases able to open them perfectly fine consistently. How fast is your internet speed and what is your CPU? I am wondering if it's possible that it lags out and is causing the timing to get messed up. Are the cases that aren't being opened towards the end or just completely random?

I have 750/750 internet and Ryzen 7700x CPU.
I will re-install and let you know.

**Comment by TerminatorIsGod** [comment]
I believe the issue was it was just too fast for the website. Feel free to test with the latest release.

**Comment by evenlk** [comment]
After re-install it successfully collect all cases (previous version). I'll install the new one to be safe.

**Comment by TerminatorIsGod** [comment]
I pushed a new release trying to address this issue, it seems to be related to the website's recent lag problem.
