### ISSUE TITLE
How to start ?

### ISSUE THREAD

**Issue by smokehubde** [TerminatorIsGod/CSGORoll-Daily-Rewards-Bot#6]

**Comment by TerminatorIsGod** [comment]
Download the exe from the [releases](https://github.com/TerminatorIsGod/CSGORoll-Daily-Rewards-Bot/releases/tag/Release_v1.0.3) You extract the zip and run the exe, it will take you to csgoroll's site and then you need to sign in. From there it will automatically do the rest.
