### ISSUE TITLE
Still cases missing

### ISSUE THREAD

**Issue by evenlk** [TerminatorIsGod/CSGORoll-Daily-Rewards-Bot#7]
Hi,

I've been monitoring it since the new release and there is still cases missing from time to time.
This is a big issue since when it misses 1 case, the entire automation gets broken. I've "reset" it multiple times where I wait and open all cases so it gets syncronized again, but this only last for 1 or 2 days before it eventually misses a case again. 

I think the issue is related to the part where it checks if all cases is open.

**Comment by TerminatorIsGod** [comment]
It has to do with CSGORoll's cite being laggy. Ill look into making a proper fix rather than just band-aiding it. I should have a new release either later today or tomorrow.

**Comment by TerminatorIsGod** [comment]
I just pushed a new release, I completely rewrote how it collects cases to be actually reliable even if the website is laggy. I haven't been able to throughly test it yet, let me know how it goes.

**Comment by TerminatorIsGod** [comment]
I have done some minor testing, [v1.1.2](https://github.com/TerminatorIsGod/CSGORoll-Daily-Rewards-Bot/releases/tag/Release_v1.1.2) seems to be working well. It's a huge improvement from v1,0, hopefully it will collect your dailies without any more problems.
