### ISSUE TITLE
Program "freeze"

### ISSUE THREAD

**Issue by evenlk** [TerminatorIsGod/CSGORoll-Daily-Rewards-Bot#8]
Hello!

So today when it opened, it didn't do anything when the cases where ready to open. It had the level 2 case window open, but didn't open the case.
The last message in console was "all cases open, 8 seconds remaining". 
I left it for a couple of minutes before closing it and reopening it, and it worked fine.
Only difference was that the "Subscribe to our newsletter" message was present when it wasn't working, when it worked the message was not present. Not sure if it is related our not.

**Comment by evenlk** [comment]
Fyi, this is with the newest release.

**Comment by TerminatorIsGod** [comment]
This is fixed in 1.1.3 and [1.1.4](https://github.com/TerminatorIsGod/CSGORoll-Daily-Rewards-Bot/releases/tag/Release_v1.1.4)
